_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 55
            "2":
                - 1
                - 2
                - 3
                - 12
                - 41
                - 55
            "3":
                - 2
                - 13
                - 14
                - 23
                - 55
            "4": 3.10.8
            "5": 0.18.5
            "8":
                - 1
                - 5
            "9":
                "2": Avalanche
            "12": 0.18.5
            "13": linux-x86_64
